### ISSUE TITLE
Many "please recompile" messages

### ISSUE THREAD

**Issue by cquiroz** [laughedelic/atom-ide-scala#20]
This message tends to appear a lot while coding:

![screenshot 2017-12-01 15 59 03](https://user-images.githubusercontent.com/3615303/33498784-76f0519e-d6b1-11e7-9e2a-de9b823f9422.png)

**Comment by laughedelic** [comment]
Hey @cquiroz! 👋  I have a hacky fix for you 😉 Check #22 and let me know what you think.
