### ISSUE TITLE
Add language-scala and atom-ide-ui as package dependencies

### ISSUE THREAD

**Issue by ghisvail** [laughedelic/atom-ide-scala#24]
To ease the installation process. Instead of having to manually install those according to the instructions in the README, we might as well automate their installation. This is what is done for [atom-ide-rust](https://github.com/mehcode/atom-ide-rust/blob/6e8e248c0218d333c9346673945334e389b8fffc/package.json#L13) for instance.

**Comment by laughedelic** [comment]
* https://discuss.atom.io/t/depending-on-other-packages/2360/26
* https://github.com/atom/apm/issues/288

I thought that it's not supported by Atom/apm, but now I searched and found that there is [atom-package-deps](https://www.npmjs.com/package/atom-package-deps) package implementing this functionality (and now I see that atom-ide-rust uses it).

I will add it. Thanks for the suggestion 👍
