### ISSUE TITLE
Add server commands

### ISSUE THREAD

**Issue by laughedelic** [laughedelic/atom-ide-scala#27]
* clear index cache: https://github.com/scalameta/language-server/pull/131
* reset presentation compiler: https://github.com/scalameta/language-server/pull/135

https://atom.io/docs/api/v1.23.1/CommandRegistry

**Comment by laughedelic** [comment]
@Jarlakxen are you interested in implementing this?

**Comment by Jarlakxen** [comment]
Sure! =)

**Comment by laughedelic** [comment]
Fixed in #34
