### ISSUE TITLE
Move the release notes to CHANGELOG.md

### ISSUE THREAD

**Issue by ghisvail** [laughedelic/atom-ide-scala#28]
Please consider moving the release notes listed under `notes/` to a single `CHANGELOG.md` file in the root of the repository. This way, the release notes will be accessible from within the Atom (under CHANGELOG) and can be read without having to browse the source code on GitHub. Thanks.

**Comment by ghisvail** [comment]
Also, a section is missing for `v0.5.0`.

**Comment by laughedelic** [comment]
I actually intended to do it and the latest release has `CHANGELOG.md`: [repo at v0.5.0](https://github.com/laughedelic/atom-ide-scala/tree/v0.5.0). But I don't know how Atom actually uses it. It seems that the file presence in the repo at the release tag (which is what you get locally when you install the plugin) is not enough. Does it need some special formatting or does Atom use it from Github?

Missing `notes/0.5.0.markdown` was unrelated, I commited it on release, but forgot to push 😅

**Comment by laughedelic** [comment]
@ghisvail try the new v0.6.0:

<img width="620" alt="screen shot 2018-04-15 at 05 01 43" src="https://user-images.githubusercontent.com/766656/38774469-3545d21e-406a-11e8-9fee-d8694426844d.png">

There's a CHANGELOG button and it does open release notes 👍
