### ISSUE TITLE
Improve warnings

### ISSUE THREAD

**Issue by laughedelic** [laughedelic/atom-ide-scala#58]
After #53 there are different types of warnings when you open a new project which is not setup for any language server: see https://github.com/laughedelic/atom-ide-scala/pull/53#issuecomment-381374198.

* they should look different to be less confusing
* they shouldn't appear on every new file open

**Comment by sammynammari** [comment]
I've noticed that if set the default language server to Metals and have "Choose server based on the project setup" unchecked, I get the yellow "Project is not setup, using default language server: Metals" message. But, Metals starts up and runs just fine.

Also, me and my coworkers are really excited about this and Metals. Thanks for the hard work :)

**Comment by laughedelic** [comment]
Yep, this is expected behaviour, but it's confusing, indeed. That's why I opened this issue. I didn't test enough various usage scenarios before I released 0.6.0. But I'll improve it this week. 

Still though, this warning is valid at the moment: it was meant to make you aware that you need to _setup_ the project to use Metals in it. This process will get simplified a lot in Metals for the sbt 1.x users: https://github.com/scalameta/metals/pull/287, but at the moment you should follow Metals installation instructions to prepare your projects. Without it server will start, but most features just won't work.

> Also, me and my coworkers are really excited about this and Metals. Thanks for the hard work :)

Cool! I'm glad to hear it!
