### ISSUE TITLE
Notify scalafmt failures

### ISSUE THREAD

**Issue by cquiroz** [laughedelic/atom-ide-scala#59]
When scalafmt fails there is no notification and the tooltip doesn't disappear

<img width="203" alt="gmoscontrollerepics scala projects ocs3 2018-04-15 11-15-13" src="https://user-images.githubusercontent.com/3615303/38779503-cbc77802-409f-11e8-9654-dc1f733a3f5f.png">

**Comment by laughedelic** [comment]
Do you run formatting while Metals is still initialising? I'm not sure what I can do about that from here. I think this should be fixed either in atom-languageclient or in atom-ide-ui. It should just ignore formatting request until the server is initialised.

**Comment by cquiroz** [comment]
This happened later on. i pressed the shortcut for formatting and you can see the error in the log but there is no indication on the UI

**Comment by laughedelic** [comment]
Could you post the failure log? Why does it fail at all?

**Comment by cquiroz** [comment]
The scala file is to complex and scalfmt files. That's unrelated to the plugin of course
```
Scalafmt210:58 Failed to format file file:///Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala. Cause: Search state exploded around line 26.
00:14:42.773 INFO  s.m.m.s.InMemorySymbolIndex - resolveName at Uri(file:///Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala):20:47
00:14:42.892 INFO  s.m.m.p.DocumentHighlightProvider$ - Document highlight in Uri(file:///Users/cquiroz/Projects/ocs3/modules/edu.gemini.seqexec.model/src/main/scala/edu/gemini/seqexec/model/events.scala
```

**Comment by laughedelic** [comment]
I see. I think it's Metals fault then: it just swallows that error instead of returning a proper error LSP response. Could you open an issue in Metals?
