### ISSUE TITLE
Restore scalafmt on save

### ISSUE THREAD

**Issue by cquiroz** [laughedelic/atom-ide-scala#74]
It seems with metals 4.0 scalafmt could be enabled in Atom again. That would be very useful

**Comment by cquiroz** [comment]
I'd really like to get this back. Perhaps if you give me some pointers I could try working on it

**Comment by laughedelic** [comment]
Hi @cquiroz. scalafmt should work as before, but Metals doesn't have a config setting for running it on save. You can enable it in the ide-ui package though:

<img width="631" alt="Screenshot 2019-06-23 at 20 12 18" src="https://user-images.githubusercontent.com/766656/59980314-6f195200-95f4-11e9-8c19-b7131b455009.png">

**Comment by laughedelic** [comment]
The difference is that this will enable formatting on save for any other language servers if you use any.
You can also run formatting manually with a hotkey (see it below the ide-ui settings).

Of course, it still can be implemented as a specialized setting in the ide-scala plugin. Let me know if none of the above options fit you and you still want this feature.

**Comment by cquiroz** [comment]
I see, that option should be more than enough. Thanks
