### ISSUE TITLE
Does this package still work?

### ISSUE THREAD

**Issue by steffansluis** [laughedelic/atom-ide-scala#76]
I've tried multiple times to get this working, I'm being sent all over the place to install separate plugins globally and enable settings, I've tried with both Metals and Dotty to no avail. Does anyone know if the current version of this package still works, and if so, what the required steps are to get it working?

**Comment by olafurpg** [comment]
This package works for me

- have you tried installing language-scala separately?
- have you tried updating the metals version to 0.4.4?

**Comment by laughedelic** [comment]
@steffansluis please try the new version 0.9.0. Let me know if it doesn't work for you for some reason.
